name: tests

on: [push, pull_request]

jobs:
 tests:
  runs-on: ubuntu-latest

  strategy:
   fail-fast: true
   matrix:
    php: [7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
    elastic: [7.11.0]
    stability: [prefer-lowest, prefer-stable]
    exclude:
     - php: 8.1
       stability: prefer-lowest
     - php: 8.2
       stability: prefer-lowest
     - php: 8.3
       stability: prefer-lowest
     - php: 8.4
       stability: prefer-lowest
  name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

  steps:
   - name: Checkout code
     uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
   - name: Setup PHP
     uses: setup-php/setup-php@46ae35f3338b644fa11efcbbcd5d739c34372ae8
     with:
      php-version: ${{ matrix.php }}
      tools: composer:v2, cs2pr
      coverage: none
   - name: Setup problem matchers for PHPUnit
     run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
   - name: Get composer cache directory
     id: composer-cache
     run: echo "::set-output name=dir::$(composer config cache-files-dir)"
   - name: Cache dependencies
     uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
     with:
      path: ${{ steps.composer-cache.outputs.dir }}
      key: dependencies-${{ matrix.php }}-${{ matrix.stability }}-composer-${{ hashFiles('**/composer.lock') }}
      restore-keys: dependencies-${{ matrix.php }}-${{ matrix.stability }}-composer-
   - name: Install dependencies
     run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction
   #      - name: Check coding style
   #        run: php-cs-fixer fix --dry-run --allow-risky=true --format=checkstyle | cs2pr
   - name: Configure sysctl limits
     run: |
      sudo swapoff -a
      sudo sysctl -w vm.swappiness=1
      sudo sysctl -w fs.file-max=262144
      sudo sysctl -w vm.max_map_count=262144
   - name: Runs Elasticsearch
     uses: elastic/elastic-github-actions/elasticsearch@98431b45a60cbb6ace481778827bc8e11f12fd65 # master
     with:
      stack-version: ${{ matrix.elastic }}
   - name: Configure matchers for PHPUnit
     uses: mheap/phpunit-matcher-action@dcbd4ead41890163b65d0b21534387ce72980ee5 # v1
   - name: Run PHP tests via PHPUnit
     run: vendor/bin/phpunit --teamcity
